-- ==========================================
-- FILE: CinemaBookingDB_All_In_One_Merged_Reset.sql
-- FIXED BY CHATGPT FROM UPLOADED DB FILES
-- Purpose:
--   Full reset script for CinemaBookingDB, merged from:
--   1) cinema-booking-schema_1.sql
--   2) SCRUM-193 customer-assisted refund patch
--   3) customer-assisted refund patch additions
--   4) SCRUM-198 ticket scan DB notes
--   5) MangerAndAdmin_1 / Admin DB notes
--
-- WARNING:
--   This script DROPS and RECREATES [CinemaBookingDB].
--   Do NOT run on a database that contains real data you need to keep.
-- ==========================================


/*
============================================================
CinemaBookingDB - CLEAN & UNIFIED SCHEMA
============================================================
This script completely replaces all fragmented alterations and 
creates the entire database structure smoothly from scratch.
============================================================
*/

-- When using sqlcmd, pass -f 65001 so Vietnamese seed data is read as UTF-8.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

USE [master];
GO

IF DB_ID(N'CinemaBookingDB') IS NOT NULL
BEGIN
    ALTER DATABASE [CinemaBookingDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [CinemaBookingDB];
END
GO

CREATE DATABASE [CinemaBookingDB];
GO

USE [CinemaBookingDB];
GO

-- =========================
-- 1. BASE DICTIONARY TABLES
-- =========================

CREATE TABLE [ROLE] (
    [roleId] NVARCHAR(50) PRIMARY KEY,
    [roleName] NVARCHAR(100) NOT NULL,
    [description] NVARCHAR(500) NULL,

    CONSTRAINT [UQ_ROLE_ROLE_NAME] UNIQUE ([roleName])
);
GO

CREATE TABLE [CINEMA] (
    [cinemaId] NVARCHAR(50) PRIMARY KEY,
    [cinemaName] NVARCHAR(255) NOT NULL,
    [address] NVARCHAR(500) NOT NULL,
    [city] NVARCHAR(100) NOT NULL,
    [phoneNumber] NVARCHAR(30) NULL,
    [cinemaStatus] NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT [CK_CINEMA_STATUS] CHECK ([cinemaStatus] IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);
GO

CREATE TABLE [SEAT_TYPE] (
    [seatTypeId] NVARCHAR(50) PRIMARY KEY,
    [typeName] NVARCHAR(100) NOT NULL,
    [extraFee] DECIMAL(18,2) NOT NULL DEFAULT 0,

    CONSTRAINT [UQ_SEAT_TYPE_NAME] UNIQUE ([typeName]),
    CONSTRAINT [CK_SEAT_TYPE_EXTRA_FEE] CHECK ([extraFee] >= 0)
);
GO

CREATE TABLE [LANGUAGE] (
    [languageId] NVARCHAR(50) PRIMARY KEY,
    [name] NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE [GENRE] (
    [genreId] INT IDENTITY(1,1) PRIMARY KEY,
    [name] NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE [PAYMENT_PROVIDER] (
    [paymentProviderId] NVARCHAR(50) PRIMARY KEY,
    [providerName] NVARCHAR(100) NOT NULL,
    [apiEndpoint] NVARCHAR(1000) NULL,
    [providerStatus] NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT [UQ_PAYMENT_PROVIDER_NAME] UNIQUE ([providerName]),
    CONSTRAINT [CK_PAYMENT_PROVIDER_STATUS] CHECK ([providerStatus] IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);
GO

CREATE TABLE [FB_ITEM] (
    [fbItemId] NVARCHAR(50) PRIMARY KEY,
    [itemName] NVARCHAR(255) NOT NULL,
    [price] DECIMAL(18,2) NOT NULL,
    [itemStatus] NVARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',

    CONSTRAINT [CK_FB_ITEM_PRICE] CHECK ([price] >= 0),
    CONSTRAINT [CK_FB_ITEM_STATUS] CHECK ([itemStatus] IN ('AVAILABLE', 'UNAVAILABLE', 'INACTIVE'))
);
GO

-- =========================
-- 2. MOVIE & VOUCHER TABLES
-- =========================

CREATE TABLE [MOVIE] (
    [movieId] NVARCHAR(50) PRIMARY KEY,
    [title] NVARCHAR(255) NOT NULL,
    [durationMinutes] INT NOT NULL,
    [languageId] NVARCHAR(50) NULL,
    [releaseDate] DATE NULL,
    [ageRating] NVARCHAR(30) NULL,
    [description] NVARCHAR(MAX) NULL,
    [posterUrl] NVARCHAR(1000) NULL,
    [trailerUrl] NVARCHAR(1000) NULL,
    [director] NVARCHAR(200) NULL,
    [highlight] NVARCHAR(30) NULL,
    [movieStatus] NVARCHAR(30) NOT NULL DEFAULT 'COMING_SOON',
    [viewCount] INT NOT NULL DEFAULT 0,
    [averageRating] DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    [totalReviews] INT NOT NULL DEFAULT 0,
    [totalViews] INT NOT NULL DEFAULT 0,
    [dailyViews] INT NOT NULL DEFAULT 0,

    CONSTRAINT [CK_MOVIE_DURATION] CHECK ([durationMinutes] > 0),
    CONSTRAINT [CK_MOVIE_HIGHLIGHT] CHECK ([highlight] IS NULL OR [highlight] IN ('HOT', 'NEW', 'TRENDING')),
    CONSTRAINT [CK_MOVIE_STATUS] CHECK ([movieStatus] IN ('COMING_SOON', 'NOW_SHOWING', 'ENDED', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT [FK_MOVIE_LANGUAGE] FOREIGN KEY ([languageId]) REFERENCES [LANGUAGE]([languageId])
);
GO

CREATE TABLE [MOVIE_GENRE] (
    [movieId] NVARCHAR(50) NOT NULL,
    [genreId] INT NOT NULL,
    PRIMARY KEY ([movieId], [genreId]),
    CONSTRAINT [FK_MOVIE_GENRE_MOVIE] FOREIGN KEY ([movieId]) REFERENCES [MOVIE]([movieId]) ON DELETE CASCADE,
    CONSTRAINT [FK_MOVIE_GENRE_GENRE] FOREIGN KEY ([genreId]) REFERENCES [GENRE]([genreId]) ON DELETE CASCADE
);
GO

CREATE TABLE [VOUCHER] (
    [voucherId] NVARCHAR(50) PRIMARY KEY,
    [voucherCode] NVARCHAR(100) NOT NULL,
    [title] NVARCHAR(255) NULL,
    [description] NVARCHAR(1000) NULL,
    [imageUrl] NVARCHAR(1000) NULL,
    [discountType] NVARCHAR(30) NOT NULL,
    [discountValue] DECIMAL(18,2) NOT NULL,
    [minOrderAmount] DECIMAL(18,2) NULL,
    [maxDiscountAmount] DECIMAL(18,2) NULL,
    [usageLimit] INT NOT NULL,
    [perCustomerLimit] INT NULL,
    [usedCount] INT NOT NULL DEFAULT 0,
    [startDate] DATETIME2 NOT NULL,
    [endDate] DATETIME2 NOT NULL,
    [voucherStatus] NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT [UQ_VOUCHER_CODE] UNIQUE ([voucherCode]),
    CONSTRAINT [CK_VOUCHER_DISCOUNT_TYPE] CHECK ([discountType] IN ('AMOUNT', 'PERCENT')),
    CONSTRAINT [CK_VOUCHER_DISCOUNT_VALUE] CHECK ([discountValue] > 0),
    CONSTRAINT [CK_VOUCHER_MIN_ORDER_AMOUNT] CHECK ([minOrderAmount] IS NULL OR [minOrderAmount] >= 0),
    CONSTRAINT [CK_VOUCHER_MAX_DISCOUNT_AMOUNT] CHECK ([maxDiscountAmount] IS NULL OR [maxDiscountAmount] > 0),
    CONSTRAINT [CK_VOUCHER_USAGE_LIMIT] CHECK ([usageLimit] >= 0),
    CONSTRAINT [CK_VOUCHER_PER_CUSTOMER_LIMIT] CHECK ([perCustomerLimit] IS NULL OR [perCustomerLimit] > 0),
    CONSTRAINT [CK_VOUCHER_USED_COUNT] CHECK ([usedCount] >= 0),
    CONSTRAINT [CK_VOUCHER_DATE_RANGE] CHECK ([endDate] > [startDate]),
    CONSTRAINT [CK_VOUCHER_STATUS] CHECK ([voucherStatus] IN ('ACTIVE', 'INACTIVE', 'EXPIRED'))
);
GO

-- =========================
-- 3. USER / AUTH / PROFILE
-- =========================

CREATE TABLE [USER] (
    [userId] NVARCHAR(50) PRIMARY KEY,
    [roleId] NVARCHAR(50) NOT NULL,
    [email] NVARCHAR(255) NOT NULL,
    [passwordHash] NVARCHAR(500) NOT NULL,
    [fullName] NVARCHAR(255) NOT NULL,
    [phoneNumber] NVARCHAR(30) NULL,
    [status] NVARCHAR(30) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    [emailVerified] BIT NOT NULL DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [updatedAt] DATETIME2 NULL,
    [spamViolationCount] INT NOT NULL DEFAULT 0,
    [isBlocked] BIT NOT NULL DEFAULT 0,
    [blockedUntil] DATETIME2 NULL,

    CONSTRAINT [UQ_USER_EMAIL] UNIQUE ([email]),
    CONSTRAINT [CK_USER_STATUS] CHECK ([status] IN ('PENDING_VERIFICATION', 'ACTIVE', 'INACTIVE', 'BANNED')),
    CONSTRAINT [FK_USER_ROLE] FOREIGN KEY ([roleId]) REFERENCES [ROLE]([roleId])
);
GO

CREATE TABLE [EMAIL_VERIFICATION_TOKEN] (
    [tokenId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NOT NULL,
    [token] NVARCHAR(255) NOT NULL,
    [purpose] NVARCHAR(30) NOT NULL DEFAULT 'EMAIL_VERIFICATION',
    [attemptCount] INT NOT NULL DEFAULT 0,
    [expiredAt] DATETIME2 NOT NULL,
    [verifiedAt] DATETIME2 NULL,
    [isUsed] BIT NOT NULL DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [UQ_EMAIL_VERIFICATION_TOKEN] UNIQUE ([token]),
    CONSTRAINT [CK_EMAIL_VERIFICATION_TOKEN_PURPOSE] CHECK ([purpose] IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'EMAIL_UPDATE', 'PHONE_UPDATE', 'REGISTER', 'FORGOT_PASSWORD', 'CHANGE_EMAIL', 'UPDATE_EMAIL')),
    CONSTRAINT [CK_EMAIL_VERIFICATION_TOKEN_ATTEMPT_COUNT] CHECK ([attemptCount] >= 0),
    CONSTRAINT [CK_EMAIL_VERIFICATION_EXPIRED_AT] CHECK ([expiredAt] > [createdAt]),
    CONSTRAINT [FK_EMAIL_VERIFICATION_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [REFRESH_TOKEN] (
    [refreshTokenId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NOT NULL,
    [tokenHash] NVARCHAR(450) NOT NULL,
    [issuedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [expiresAt] DATETIME2 NOT NULL,
    [revokedAt] DATETIME2 NULL,
    [isRevoked] BIT NOT NULL DEFAULT 0,

    CONSTRAINT [UQ_REFRESH_TOKEN_HASH] UNIQUE ([tokenHash]),
    CONSTRAINT [CK_REFRESH_TOKEN_EXPIRES_AT] CHECK ([expiresAt] > [issuedAt]),
    CONSTRAINT [FK_REFRESH_TOKEN_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [CUSTOMER_PROFILE] (
    [customerProfileId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NOT NULL,
    [memberLevel] NVARCHAR(30) NOT NULL DEFAULT 'STANDARD',
    [rewardPoints] INT NOT NULL DEFAULT 0,
    [dateOfBirth] DATE NULL,
    [gender] NVARCHAR(20) NULL,
    [identityCard] NVARCHAR(50) NULL,
    [address] NVARCHAR(500) NULL,
    [avatarUrl] NVARCHAR(1000) NULL,

    CONSTRAINT [UQ_CUSTOMER_PROFILE_USER] UNIQUE ([userId]),
    CONSTRAINT [CK_CUSTOMER_PROFILE_MEMBER_LEVEL] CHECK ([memberLevel] IN ('STANDARD', 'SILVER', 'GOLD', 'PLATINUM')),
    CONSTRAINT [CK_CUSTOMER_PROFILE_REWARD_POINTS] CHECK ([rewardPoints] >= 0),
    CONSTRAINT [FK_CUSTOMER_PROFILE_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [CUSTOMER_VOUCHER] (
    [customerVoucherId] NVARCHAR(50) PRIMARY KEY,
    [customerProfileId] NVARCHAR(50) NOT NULL,
    [voucherId] NVARCHAR(50) NOT NULL,
    [claimedAt] DATETIME2 NOT NULL,
    [isUsed] BIT NOT NULL DEFAULT 0,
    [usedAt] DATETIME2 NULL,

    CONSTRAINT [FK_CUSTOMER_VOUCHER_CUSTOMER_PROFILE] FOREIGN KEY ([customerProfileId]) REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_CUSTOMER_VOUCHER_VOUCHER] FOREIGN KEY ([voucherId]) REFERENCES [VOUCHER]([voucherId])
);
GO

CREATE TABLE [STAFF_PROFILE] (
    [staffProfileId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NOT NULL,
    [cinemaId] NVARCHAR(50) NOT NULL,
    [position] NVARCHAR(100) NOT NULL,
    [hireDate] DATE NULL,
    [dateOfBirth] DATE NULL,
    [gender] NVARCHAR(20) NULL,
    [identityCard] NVARCHAR(50) NULL,
    [address] NVARCHAR(500) NULL,
    [avatarUrl] NVARCHAR(1000) NULL,
    [employmentStatus] NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT [UQ_STAFF_PROFILE_USER] UNIQUE ([userId]),
    CONSTRAINT [CK_STAFF_PROFILE_EMPLOYMENT_STATUS] CHECK ([employmentStatus] IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT [FK_STAFF_PROFILE_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId]),
    CONSTRAINT [FK_STAFF_PROFILE_CINEMA] FOREIGN KEY ([cinemaId]) REFERENCES [CINEMA]([cinemaId])
);
GO

-- =========================
-- 4. CINEMA STRUCTURE
-- =========================

CREATE TABLE [ROOM] (
    [roomId] NVARCHAR(50) PRIMARY KEY,
    [cinemaId] NVARCHAR(50) NOT NULL,
    [roomName] NVARCHAR(100) NOT NULL,
    [capacity] INT NOT NULL,
    [roomStatus] NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT [UQ_ROOM_CINEMA_ROOM_NAME] UNIQUE ([cinemaId], [roomName]),
    CONSTRAINT [CK_ROOM_CAPACITY] CHECK ([capacity] > 0),
    CONSTRAINT [CK_ROOM_STATUS] CHECK ([roomStatus] IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CONSTRAINT [FK_ROOM_CINEMA] FOREIGN KEY ([cinemaId]) REFERENCES [CINEMA]([cinemaId])
);
GO

CREATE TABLE [SEAT] (
    [seatId] NVARCHAR(50) PRIMARY KEY,
    [roomId] NVARCHAR(50) NOT NULL,
    [seatTypeId] NVARCHAR(50) NOT NULL,
    [seatCode] NVARCHAR(20) NOT NULL,
    [rowLabel] NVARCHAR(10) NOT NULL,
    [seatNumber] INT NOT NULL,
    [isActive] BIT NOT NULL DEFAULT 1,

    CONSTRAINT [UQ_SEAT_ROOM_SEAT_CODE] UNIQUE ([roomId], [seatCode]),
    CONSTRAINT [UQ_SEAT_ROOM_ROW_NUMBER] UNIQUE ([roomId], [rowLabel], [seatNumber]),
    CONSTRAINT [CK_SEAT_NUMBER] CHECK ([seatNumber] > 0),
    CONSTRAINT [FK_SEAT_ROOM] FOREIGN KEY ([roomId]) REFERENCES [ROOM]([roomId]),
    CONSTRAINT [FK_SEAT_SEAT_TYPE] FOREIGN KEY ([seatTypeId]) REFERENCES [SEAT_TYPE]([seatTypeId])
);
GO

-- =========================
-- 5. SHOWTIME
-- =========================

CREATE TABLE [SHOWTIME] (
    [showtimeId] NVARCHAR(50) PRIMARY KEY,
    [movieId] NVARCHAR(50) NOT NULL,
    [roomId] NVARCHAR(50) NOT NULL,
    [startTime] DATETIME2 NOT NULL,
    [endTime] DATETIME2 NOT NULL,
    [basePrice] DECIMAL(18,2) NOT NULL DEFAULT 0,
    [status] NVARCHAR(30) NOT NULL DEFAULT 'OPEN',
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [CK_SHOWTIME_TIME_RANGE] CHECK ([endTime] > [startTime]),
    CONSTRAINT [CK_SHOWTIME_BASE_PRICE] CHECK ([basePrice] >= 0),
    CONSTRAINT [CK_SHOWTIME_STATUS] CHECK ([status] IN ('OPEN', 'CLOSED', 'CANCELLED', 'COMPLETED', 'SUSPENDED', 'PROCESSING_UNSTABLE')),
    CONSTRAINT [FK_SHOWTIME_MOVIE] FOREIGN KEY ([movieId]) REFERENCES [MOVIE]([movieId]),
    CONSTRAINT [FK_SHOWTIME_ROOM] FOREIGN KEY ([roomId]) REFERENCES [ROOM]([roomId])
);
GO

CREATE TABLE [SHOWTIME_SEAT] (
    [showtimeSeatId] NVARCHAR(50) PRIMARY KEY,
    [showtimeId] NVARCHAR(50) NOT NULL,
    [seatId] NVARCHAR(50) NOT NULL,
    [seatStatus] NVARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    [lockedUntil] DATETIME2 NULL,
    [lockedByUserId] NVARCHAR(50) NULL,
    [rowVersion] ROWVERSION,

    CONSTRAINT [UQ_SHOWTIME_SEAT_SHOWTIME_SEAT] UNIQUE ([showtimeId], [seatId]),
    CONSTRAINT [CK_SHOWTIME_SEAT_STATUS] CHECK ([seatStatus] IN ('AVAILABLE', 'LOCKED', 'BOOKED', 'RELEASED', 'UNAVAILABLE')),
    CONSTRAINT [FK_SHOWTIME_SEAT_SHOWTIME] FOREIGN KEY ([showtimeId]) REFERENCES [SHOWTIME]([showtimeId]),
    CONSTRAINT [FK_SHOWTIME_SEAT_SEAT] FOREIGN KEY ([seatId]) REFERENCES [SEAT]([seatId]),
    CONSTRAINT [FK_SHOWTIME_SEAT_LOCKED_BY_USER] FOREIGN KEY ([lockedByUserId]) REFERENCES [USER]([userId])
);
GO

-- =========================
-- 6. BOOKING / TICKET
-- =========================

CREATE TABLE [BOOKING] (
    [bookingId] NVARCHAR(50) PRIMARY KEY,
    [customerProfileId] NVARCHAR(50) NULL,
    [showtimeId] NVARCHAR(50) NOT NULL,
    [createdByStaffProfileId] NVARCHAR(50) NULL,
    [fbFulfilledByStaffProfileId] NVARCHAR(50) NULL,
    [bookingChannel] NVARCHAR(30) NOT NULL DEFAULT 'ONLINE',
    [guestName] NVARCHAR(255) NULL,
    [guestPhone] NVARCHAR(30) NULL,
    [guestEmail] NVARCHAR(255) NULL,
    [bookingStatus] NVARCHAR(30) NOT NULL DEFAULT 'CREATED',
    [totalAmount] DECIMAL(18,2) NOT NULL DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [expiredAt] DATETIME2 NULL,
    [fbFulfillmentStatus] NVARCHAR(30) NOT NULL DEFAULT 'NOT_APPLICABLE',
    [fbFulfilledAt] DATETIME2 NULL,
    [clientRequestId] UNIQUEIDENTIFIER NULL,
    [requestFingerprint] VARCHAR(64) NULL,

    CONSTRAINT [CK_BOOKING_STATUS] CHECK ([bookingStatus] IN ('CREATED', 'PENDING_PAYMENT', 'PAID', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', 'COMPLETED', 'PROCESSING_UNSTABLE')),
    CONSTRAINT [CK_BOOKING_CHANNEL] CHECK ([bookingChannel] IN ('ONLINE', 'COUNTER')),
    CONSTRAINT [CK_BOOKING_FB_FULFILLMENT_STATUS] CHECK ([fbFulfillmentStatus] IN ('NOT_APPLICABLE', 'PENDING', 'PREPARING', 'FULFILLED', 'CANCELLED')),
    CONSTRAINT [CK_BOOKING_ONLINE_CUSTOMER_REQUIRED] CHECK ([bookingChannel] <> 'ONLINE' OR [customerProfileId] IS NOT NULL),
    CONSTRAINT [CK_BOOKING_TOTAL_AMOUNT] CHECK ([totalAmount] >= 0),
    CONSTRAINT [FK_BOOKING_CUSTOMER_PROFILE] FOREIGN KEY ([customerProfileId]) REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_BOOKING_SHOWTIME] FOREIGN KEY ([showtimeId]) REFERENCES [SHOWTIME]([showtimeId]),
    CONSTRAINT [FK_BOOKING_CREATED_BY_STAFF] FOREIGN KEY ([createdByStaffProfileId]) REFERENCES [STAFF_PROFILE]([staffProfileId]),
    CONSTRAINT [FK_BOOKING_FB_FULFILLED_BY_STAFF] FOREIGN KEY ([fbFulfilledByStaffProfileId]) REFERENCES [STAFF_PROFILE]([staffProfileId])
);
GO

CREATE TABLE [BOOKING_SEAT] (
    [bookingSeatId] NVARCHAR(50) PRIMARY KEY,
    [bookingId] NVARCHAR(50) NOT NULL,
    [showtimeSeatId] NVARCHAR(50) NOT NULL,
    [seatPrice] DECIMAL(18,2) NOT NULL,

    CONSTRAINT [UQ_BOOKING_SEAT_SHOWTIME_SEAT] UNIQUE ([showtimeSeatId]),
    CONSTRAINT [CK_BOOKING_SEAT_PRICE] CHECK ([seatPrice] >= 0),
    CONSTRAINT [FK_BOOKING_SEAT_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId]),
    CONSTRAINT [FK_BOOKING_SEAT_SHOWTIME_SEAT] FOREIGN KEY ([showtimeSeatId]) REFERENCES [SHOWTIME_SEAT]([showtimeSeatId])
);
GO

CREATE TABLE [TICKET] (
    [ticketId] NVARCHAR(50) PRIMARY KEY,
    [bookingSeatId] NVARCHAR(50) NOT NULL,
    [qrCode] NVARCHAR(450) NOT NULL,
    [ticketStatus] NVARCHAR(30) NOT NULL DEFAULT 'UNUSED',
    [generatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [UQ_TICKET_BOOKING_SEAT] UNIQUE ([bookingSeatId]),
    CONSTRAINT [UQ_TICKET_QR_CODE] UNIQUE ([qrCode]),
    CONSTRAINT [CK_TICKET_STATUS] CHECK ([ticketStatus] IN ('GENERATED', 'UNUSED', 'CHECKED_IN', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT [FK_TICKET_BOOKING_SEAT] FOREIGN KEY ([bookingSeatId]) REFERENCES [BOOKING_SEAT]([bookingSeatId])
);
GO

CREATE TABLE [CHECKIN_LOG] (
    [checkInLogId] NVARCHAR(50) PRIMARY KEY,
    [ticketId] NVARCHAR(50) NULL,
    [staffProfileId] NVARCHAR(50) NULL,
    [scannedByUserId] NVARCHAR(50) NOT NULL,
    [scanTime] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [result] NVARCHAR(30) NOT NULL,
    [failureReason] NVARCHAR(500) NULL,
    [rawQrCode] NVARCHAR(450) NULL,

    CONSTRAINT [CK_CHECKIN_LOG_RESULT] CHECK ([result] IN ('SUCCESS', 'FAILED')),
    CONSTRAINT [FK_CHECKIN_LOG_TICKET] FOREIGN KEY ([ticketId]) REFERENCES [TICKET]([ticketId]),
    CONSTRAINT [FK_CHECKIN_LOG_STAFF_PROFILE] FOREIGN KEY ([staffProfileId]) REFERENCES [STAFF_PROFILE]([staffProfileId]),
    CONSTRAINT [FK_CHECKIN_LOG_SCANNED_BY_USER] FOREIGN KEY ([scannedByUserId]) REFERENCES [USER]([userId])
);
GO

-- =========================
-- 7. PAYMENT / REFUND
-- =========================

CREATE TABLE [PAYMENT] (
    [paymentId] NVARCHAR(50) PRIMARY KEY,
    [bookingId] NVARCHAR(50) NOT NULL,
    [paymentProviderId] NVARCHAR(50) NOT NULL,
    [amount] DECIMAL(18,2) NOT NULL,
    [paymentMethod] NVARCHAR(50) NULL,
    [transactionCode] NVARCHAR(255) NULL,
    [providerTransactionCode] NVARCHAR(255) NULL,
    [paymentStatus] NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    [failureReason] NVARCHAR(1000) NULL,
    [rawCallbackPayload] NVARCHAR(MAX) NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [updatedAt] DATETIME2 NULL,
    [paidAt] DATETIME2 NULL,

    CONSTRAINT [CK_PAYMENT_AMOUNT] CHECK ([amount] >= 0),
    CONSTRAINT [CK_PAYMENT_STATUS] CHECK ([paymentStatus] IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT [FK_PAYMENT_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId]),
    CONSTRAINT [FK_PAYMENT_PAYMENT_PROVIDER] FOREIGN KEY ([paymentProviderId]) REFERENCES [PAYMENT_PROVIDER]([paymentProviderId])
);
GO

CREATE TABLE [SHOWTIME_CANCELLATION] (
    [showtimeCancellationId] NVARCHAR(50) PRIMARY KEY,
    [showtimeId] NVARCHAR(50) NOT NULL,
    [cancelledByUserId] NVARCHAR(50) NOT NULL,
    [cancelledByStaffId] NVARCHAR(50) NULL,
    [cancelReason] NVARCHAR(1000) NOT NULL,
    [cancelledAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [UQ_SHOWTIME_CANCELLATION_SHOWTIME] UNIQUE ([showtimeId]),
    CONSTRAINT [FK_SHOWTIME_CANCELLATION_SHOWTIME] FOREIGN KEY ([showtimeId]) REFERENCES [SHOWTIME]([showtimeId]),
    CONSTRAINT [FK_SHOWTIME_CANCELLATION_USER] FOREIGN KEY ([cancelledByUserId]) REFERENCES [USER]([userId]),
    CONSTRAINT [FK_SHOWTIME_CANCELLATION_STAFF_PROFILE] FOREIGN KEY ([cancelledByStaffId]) REFERENCES [STAFF_PROFILE]([staffProfileId])
);
GO

CREATE TABLE [REFUND] (
    [refundId] NVARCHAR(50) PRIMARY KEY,
    [bookingId] NVARCHAR(50) NOT NULL,
    [paymentId] NVARCHAR(50) NOT NULL,
    [paymentProviderId] NVARCHAR(50) NOT NULL,
    [showtimeCancellationId] NVARCHAR(50) NULL,
    [refundAmount] DECIMAL(18,2) NOT NULL,
    [refundStatus] NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    [refundReason] NVARCHAR(1000) NULL,
    [providerRefundCode] NVARCHAR(255) NULL,
    [failureReason] NVARCHAR(1000) NULL,
    [requestedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [refundedAt] DATETIME2 NULL,

    CONSTRAINT [CK_REFUND_AMOUNT] CHECK ([refundAmount] > 0),
    CONSTRAINT [CK_REFUND_STATUS] CHECK ([refundStatus] IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REQUESTED', 'MANUAL_REQUIRED')),
    CONSTRAINT [FK_REFUND_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId]),
    CONSTRAINT [FK_REFUND_PAYMENT] FOREIGN KEY ([paymentId]) REFERENCES [PAYMENT]([paymentId]),
    CONSTRAINT [FK_REFUND_PAYMENT_PROVIDER] FOREIGN KEY ([paymentProviderId]) REFERENCES [PAYMENT_PROVIDER]([paymentProviderId]),
    CONSTRAINT [FK_REFUND_SHOWTIME_CANCELLATION] FOREIGN KEY ([showtimeCancellationId]) REFERENCES [SHOWTIME_CANCELLATION]([showtimeCancellationId])
);
GO

CREATE TABLE [BANK_DIRECTORY] (
    [bankCode] NVARCHAR(20) PRIMARY KEY,
    [bankBin] NVARCHAR(20) NOT NULL,
    [shortName] NVARCHAR(100) NOT NULL,
    [fullName] NVARCHAR(255) NOT NULL,
    [isActive] BIT NOT NULL DEFAULT 1,
    [supportsAccountInquiry] BIT NOT NULL DEFAULT 0,
    [supportsPayout] BIT NOT NULL DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [updatedAt] DATETIME2 NULL,

    CONSTRAINT [UQ_BANK_DIRECTORY_BIN] UNIQUE ([bankBin])
);
GO

CREATE TABLE [REFUND_CLAIM] (
    [refundClaimId] NVARCHAR(50) PRIMARY KEY,
    [refundId] NVARCHAR(50) NOT NULL,
    [customerProfileId] NVARCHAR(50) NOT NULL,
    [bankCode] NVARCHAR(20) NULL,
    [claimStatus] NVARCHAR(30) NOT NULL DEFAULT 'PENDING_INFO',
    [accountValidationStatus] NVARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    [bankAccountEncrypted] VARBINARY(MAX) NULL,
    [bankAccountLast4] NVARCHAR(4) NULL,
    [accountHolderNameEncrypted] VARBINARY(MAX) NULL,
    [verifiedAccountHolderNameEncrypted] VARBINARY(MAX) NULL,
    [verificationProvider] NVARCHAR(100) NULL,
    [verificationReferenceCode] NVARCHAR(255) NULL,
    [verificationFailureReason] NVARCHAR(1000) NULL,
    [expiresAt] DATETIME2 NOT NULL,
    [submittedAt] DATETIME2 NULL,
    [processingAt] DATETIME2 NULL,
    [completedAt] DATETIME2 NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [updatedAt] DATETIME2 NULL,
    [rowVersion] ROWVERSION,

    CONSTRAINT [UQ_REFUND_CLAIM_REFUND] UNIQUE ([refundId]),
    CONSTRAINT [CK_REFUND_CLAIM_STATUS] CHECK ([claimStatus] IN
        ('PENDING_INFO', 'VERIFIED', 'SUBMITTED', 'PROCESSING',
         'COMPLETED', 'EXPIRED', 'MANUAL_REQUIRED', 'REVOKED')),
    CONSTRAINT [CK_REFUND_CLAIM_ACCOUNT_VALIDATION_STATUS]
        CHECK ([accountValidationStatus] IN
            ('NOT_STARTED', 'VERIFIED', 'FAILED', 'UNAVAILABLE')),
    CONSTRAINT [FK_REFUND_CLAIM_REFUND]
        FOREIGN KEY ([refundId]) REFERENCES [REFUND]([refundId]),
    CONSTRAINT [FK_REFUND_CLAIM_CUSTOMER_PROFILE]
        FOREIGN KEY ([customerProfileId])
        REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_REFUND_CLAIM_BANK_DIRECTORY]
        FOREIGN KEY ([bankCode]) REFERENCES [BANK_DIRECTORY]([bankCode])
);
GO

CREATE TABLE [REFUND_CLAIM_TOKEN] (
    [refundClaimTokenId] NVARCHAR(50) PRIMARY KEY,
    [refundClaimId] NVARCHAR(50) NOT NULL,
    [tokenHash] CHAR(64) NOT NULL,
    [expiresAt] DATETIME2 NOT NULL,
    [usedAt] DATETIME2 NULL,
    [revokedAt] DATETIME2 NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [UQ_REFUND_CLAIM_TOKEN_HASH] UNIQUE ([tokenHash]),
    CONSTRAINT [FK_REFUND_CLAIM_TOKEN_CLAIM]
        FOREIGN KEY ([refundClaimId])
        REFERENCES [REFUND_CLAIM]([refundClaimId])
);
GO


CREATE TABLE [REFUND_PAYOUT_ATTEMPT] (
    [refundPayoutAttemptId] NVARCHAR(50) PRIMARY KEY,
    [refundId] NVARCHAR(50) NOT NULL,
    [refundClaimId] NVARCHAR(50) NOT NULL,
    [paymentProviderId] NVARCHAR(50) NOT NULL,
    [idempotencyKey] NVARCHAR(100) NOT NULL,
    [attemptNumber] INT NOT NULL,
    [attemptStatus] NVARCHAR(30) NOT NULL DEFAULT 'CREATED',
    [providerRequestId] NVARCHAR(255) NULL,
    [providerTransactionCode] NVARCHAR(255) NULL,
    [failureReason] NVARCHAR(1000) NULL,
    [requestedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [respondedAt] DATETIME2 NULL,
    [confirmedAt] DATETIME2 NULL,

    CONSTRAINT [UQ_REFUND_PAYOUT_ATTEMPT_IDEMPOTENCY_KEY] UNIQUE ([idempotencyKey]),
    CONSTRAINT [UQ_REFUND_PAYOUT_ATTEMPT_NUMBER] UNIQUE ([refundId], [attemptNumber]),
    CONSTRAINT [CK_REFUND_PAYOUT_ATTEMPT_NUMBER] CHECK ([attemptNumber] > 0),
    CONSTRAINT [CK_REFUND_PAYOUT_ATTEMPT_STATUS] CHECK ([attemptStatus] IN
        ('CREATED', 'SUBMITTED', 'ACCEPTED', 'CONFIRMED', 'FAILED', 'UNKNOWN')),
    CONSTRAINT [FK_REFUND_PAYOUT_ATTEMPT_REFUND]
        FOREIGN KEY ([refundId]) REFERENCES [REFUND]([refundId]),
    CONSTRAINT [FK_REFUND_PAYOUT_ATTEMPT_CLAIM]
        FOREIGN KEY ([refundClaimId]) REFERENCES [REFUND_CLAIM]([refundClaimId]),
    CONSTRAINT [FK_REFUND_PAYOUT_ATTEMPT_PAYMENT_PROVIDER]
        FOREIGN KEY ([paymentProviderId]) REFERENCES [PAYMENT_PROVIDER]([paymentProviderId])
);
GO

CREATE TABLE [CUSTOMER_REFUND_REQUEST] (
    [customerRefundRequestId] NVARCHAR(50) PRIMARY KEY,
    [refundId] NVARCHAR(50) NOT NULL,
    [customerProfileId] NVARCHAR(50) NOT NULL,
    [ticketId] NVARCHAR(50) NULL,
    [requestReason] NVARCHAR(1000) NOT NULL,
    [requestStatus] NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    [processedByUserId] NVARCHAR(50) NULL,
    [processedAt] DATETIME2 NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [CK_CUSTOMER_REFUND_REQUEST_STATUS]
        CHECK ([requestStatus] IN ('PENDING', 'FULFILLED', 'REJECTED')),
    CONSTRAINT [FK_CUSTOMER_REFUND_REQUEST_REFUND]
        FOREIGN KEY ([refundId]) REFERENCES [REFUND]([refundId]),
    CONSTRAINT [FK_CUSTOMER_REFUND_REQUEST_CUSTOMER_PROFILE]
        FOREIGN KEY ([customerProfileId])
        REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_CUSTOMER_REFUND_REQUEST_TICKET]
        FOREIGN KEY ([ticketId]) REFERENCES [TICKET]([ticketId]),
    CONSTRAINT [FK_CUSTOMER_REFUND_REQUEST_PROCESSED_BY_USER]
        FOREIGN KEY ([processedByUserId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [MANUAL_REFUND_PROCESS] (
    [manualRefundProcessId] NVARCHAR(50) PRIMARY KEY,
    [refundId] NVARCHAR(50) NOT NULL,
    [refundClaimId] NVARCHAR(50) NOT NULL,
    [assignedToUserId] NVARCHAR(50) NULL,
    [processStatus] NVARCHAR(30) NOT NULL DEFAULT 'OPEN',
    [bankTransactionCode] NVARCHAR(255) NULL,
    [transferredAmount] DECIMAL(18,2) NULL,
    [proofUrl] NVARCHAR(1000) NULL,
    [adminNote] NVARCHAR(1000) NULL,
    [assignedAt] DATETIME2 NULL,
    [confirmedAt] DATETIME2 NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [rowVersion] ROWVERSION,

    CONSTRAINT [UQ_MANUAL_REFUND_PROCESS_REFUND] UNIQUE ([refundId]),
    CONSTRAINT [UQ_MANUAL_REFUND_PROCESS_CLAIM] UNIQUE ([refundClaimId]),
    CONSTRAINT [CK_MANUAL_REFUND_PROCESS_STATUS]
        CHECK ([processStatus] IN
            ('OPEN', 'IN_PROGRESS', 'CONFIRMED', 'REJECTED')),
    CONSTRAINT [CK_MANUAL_REFUND_TRANSFERRED_AMOUNT]
        CHECK ([transferredAmount] IS NULL OR [transferredAmount] > 0),
    CONSTRAINT [FK_MANUAL_REFUND_PROCESS_REFUND]
        FOREIGN KEY ([refundId]) REFERENCES [REFUND]([refundId]),
    CONSTRAINT [FK_MANUAL_REFUND_PROCESS_CLAIM]
        FOREIGN KEY ([refundClaimId])
        REFERENCES [REFUND_CLAIM]([refundClaimId]),
    CONSTRAINT [FK_MANUAL_REFUND_PROCESS_ASSIGNED_USER]
        FOREIGN KEY ([assignedToUserId]) REFERENCES [USER]([userId])
);
GO

CREATE INDEX [IX_REFUND_CLAIM_CUSTOMER_PROFILE_ID]
    ON [REFUND_CLAIM]([customerProfileId]);
CREATE INDEX [IX_REFUND_CLAIM_STATUS]
    ON [REFUND_CLAIM]([claimStatus], [expiresAt]);
CREATE INDEX [IX_REFUND_CLAIM_TOKEN_CLAIM]
    ON [REFUND_CLAIM_TOKEN]([refundClaimId], [expiresAt]);
CREATE INDEX [IX_CUSTOMER_REFUND_REQUEST_CUSTOMER_STATUS]
    ON [CUSTOMER_REFUND_REQUEST]
        ([customerProfileId], [requestStatus], [createdAt]);
CREATE INDEX [IX_MANUAL_REFUND_PROCESS_STATUS_CREATED]
    ON [MANUAL_REFUND_PROCESS]([processStatus], [createdAt]);
CREATE UNIQUE INDEX [UX_MANUAL_REFUND_BANK_TRANSACTION_CODE]
    ON [MANUAL_REFUND_PROCESS]([bankTransactionCode])
    WHERE [bankTransactionCode] IS NOT NULL;
GO

-- =========================
-- 8. VOUCHER USAGE / F&B BOOKING
-- =========================

CREATE TABLE [VOUCHER_USAGE] (
    [voucherUsageId] NVARCHAR(50) PRIMARY KEY,
    [voucherId] NVARCHAR(50) NOT NULL,
    [customerProfileId] NVARCHAR(50) NOT NULL,
    [bookingId] NVARCHAR(50) NOT NULL,
    [discountAmount] DECIMAL(18,2) NOT NULL DEFAULT 0,
    [usageStatus] NVARCHAR(30) NOT NULL DEFAULT 'APPLIED',
    [usedAt] DATETIME2 NULL,

    CONSTRAINT [UQ_VOUCHER_USAGE_BOOKING] UNIQUE ([bookingId]),
    CONSTRAINT [CK_VOUCHER_USAGE_DISCOUNT_AMOUNT] CHECK ([discountAmount] >= 0),
    CONSTRAINT [CK_VOUCHER_USAGE_STATUS] CHECK ([usageStatus] IN ('APPLIED', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT [FK_VOUCHER_USAGE_VOUCHER] FOREIGN KEY ([voucherId]) REFERENCES [VOUCHER]([voucherId]),
    CONSTRAINT [FK_VOUCHER_USAGE_CUSTOMER_PROFILE] FOREIGN KEY ([customerProfileId]) REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_VOUCHER_USAGE_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId])
);
GO

CREATE TABLE [BOOKING_FB_ITEM] (
    [bookingFBItemId] NVARCHAR(50) PRIMARY KEY,
    [bookingId] NVARCHAR(50) NOT NULL,
    [fbItemId] NVARCHAR(50) NOT NULL,
    [quantity] INT NOT NULL,
    [unitPrice] DECIMAL(18,2) NOT NULL,
    [subtotal] DECIMAL(18,2) NOT NULL,

    CONSTRAINT [CK_BOOKING_FB_ITEM_QUANTITY] CHECK ([quantity] > 0),
    CONSTRAINT [CK_BOOKING_FB_ITEM_UNIT_PRICE] CHECK ([unitPrice] >= 0),
    CONSTRAINT [CK_BOOKING_FB_ITEM_SUBTOTAL] CHECK ([subtotal] >= 0),
    CONSTRAINT [FK_BOOKING_FB_ITEM_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId]),
    CONSTRAINT [FK_BOOKING_FB_ITEM_FB_ITEM] FOREIGN KEY ([fbItemId]) REFERENCES [FB_ITEM]([fbItemId])
);
GO

CREATE TABLE [CINEMA_FB_INVENTORY] (
    [cinemaInventoryId] NVARCHAR(50) PRIMARY KEY,
    [cinemaId] NVARCHAR(50) NOT NULL,
    [fbItemId] NVARCHAR(50) NOT NULL,
    [quantity] INT NOT NULL DEFAULT 0,

    CONSTRAINT [UQ_CINEMA_FB_INVENTORY] UNIQUE ([cinemaId], [fbItemId]),
    CONSTRAINT [CK_CINEMA_FB_INVENTORY_QUANTITY] CHECK ([quantity] >= 0),
    CONSTRAINT [FK_CINEMA_FB_INVENTORY_CINEMA] FOREIGN KEY ([cinemaId]) REFERENCES [CINEMA]([cinemaId]),
    CONSTRAINT [FK_CINEMA_FB_INVENTORY_FB_ITEM] FOREIGN KEY ([fbItemId]) REFERENCES [FB_ITEM]([fbItemId])
);
GO

-- =========================
-- 9. REWARD / REVIEW / LOGS
-- =========================

CREATE TABLE [REWARD_POINT_TRANSACTION] (
    [rewardTransactionId] NVARCHAR(50) PRIMARY KEY,
    [customerProfileId] NVARCHAR(50) NOT NULL,
    [bookingId] NVARCHAR(50) NULL,
    [transactionType] NVARCHAR(30) NOT NULL,
    [points] INT NOT NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [CK_REWARD_POINT_TRANSACTION_TYPE] CHECK ([transactionType] IN ('EARN', 'REDEEM', 'REVERT', 'ADJUST')),
    CONSTRAINT [CK_REWARD_POINT_TRANSACTION_POINTS] CHECK ([points] <> 0),
    CONSTRAINT [FK_REWARD_POINT_TRANSACTION_CUSTOMER_PROFILE] FOREIGN KEY ([customerProfileId]) REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_REWARD_POINT_TRANSACTION_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId])
);
GO

CREATE TABLE [REVIEW] (
    [reviewId] NVARCHAR(50) PRIMARY KEY,
    [customerProfileId] NVARCHAR(50) NOT NULL,
    [movieId] NVARCHAR(50) NOT NULL,
    [bookingId] NVARCHAR(50) NULL,
    [rating] INT NOT NULL,
    [comment] NVARCHAR(1000) NULL,
    [status] NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    [editCount] INT NOT NULL DEFAULT 0,
    [moderatedBy] NVARCHAR(50) NULL,
    [rejectedReason] NVARCHAR(500) NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [CK_REVIEW_RATING] CHECK ([rating] BETWEEN 0 AND 5),
    CONSTRAINT [CK_REVIEW_STATUS] CHECK ([status] IN ('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED')),
    CONSTRAINT [FK_REVIEW_MODERATED_BY] FOREIGN KEY ([moderatedBy]) REFERENCES [USER]([userId]),
    CONSTRAINT [FK_REVIEW_CUSTOMER_PROFILE] FOREIGN KEY ([customerProfileId]) REFERENCES [CUSTOMER_PROFILE]([customerProfileId]),
    CONSTRAINT [FK_REVIEW_MOVIE] FOREIGN KEY ([movieId]) REFERENCES [MOVIE]([movieId]),
    CONSTRAINT [FK_REVIEW_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId])
);
GO

CREATE TABLE [REVIEW_EDIT_HISTORY] (
    [reviewEditHistoryId] NVARCHAR(50) PRIMARY KEY,
    [reviewId] NVARCHAR(50) NOT NULL,
    [oldRating] INT NOT NULL,
    [newRating] INT NOT NULL,
    [oldComment] NVARCHAR(1000) NULL,
    [newComment] NVARCHAR(1000) NULL,
    [editedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [FK_REVIEW_EDIT_HISTORY_REVIEW] FOREIGN KEY ([reviewId]) REFERENCES [REVIEW]([reviewId])
);
GO

CREATE TABLE [REVIEW_MODERATION_HISTORY] (
    [moderationHistoryId] NVARCHAR(50) PRIMARY KEY,
    [reviewId] NVARCHAR(50) NOT NULL,
    [moderatedBy] NVARCHAR(50) NOT NULL,
    [oldStatus] NVARCHAR(30) NULL,
    [newStatus] NVARCHAR(30) NOT NULL,
    [reason] NVARCHAR(1000) NULL,
    [moderatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [FK_REVIEW_MODERATION_HISTORY_REVIEW] FOREIGN KEY ([reviewId]) REFERENCES [REVIEW]([reviewId]),
    CONSTRAINT [FK_REVIEW_MODERATION_HISTORY_USER] FOREIGN KEY ([moderatedBy]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [NOTIFICATION] (
    [notificationId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NOT NULL,
    [bookingId] NVARCHAR(50) NULL,
    [title] NVARCHAR(255) NOT NULL,
    [message] NVARCHAR(1000) NOT NULL,
    [isRead] BIT NOT NULL DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [FK_NOTIFICATION_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId]),
    CONSTRAINT [FK_NOTIFICATION_BOOKING] FOREIGN KEY ([bookingId]) REFERENCES [BOOKING]([bookingId])
);
GO

CREATE TABLE [AUDIT_LOG] (
    [auditLogId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NULL,
    [action] NVARCHAR(100) NOT NULL,
    [entityName] NVARCHAR(100) NOT NULL,
    [entityId] NVARCHAR(50) NULL,
    [oldValue] NVARCHAR(MAX) NULL,
    [newValue] NVARCHAR(MAX) NULL,
    [ipAddress] NVARCHAR(100) NULL,
    [userAgent] NVARCHAR(500) NULL,
    [correlationId] NVARCHAR(100) NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [FK_AUDIT_LOG_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [CHAT_HISTORY] (
    [chatHistoryId] NVARCHAR(50) PRIMARY KEY,
    [userId] NVARCHAR(50) NULL,
    [userMessage] NVARCHAR(MAX) NOT NULL,
    [aiReplyMessage] NVARCHAR(MAX) NOT NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [FK_CHAT_HISTORY_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [MOVIE_VIEW_LOG] (
    [movieViewLogId] NVARCHAR(50) PRIMARY KEY,
    [movieId] NVARCHAR(50) NOT NULL,
    [userId] NVARCHAR(50) NULL,
    [viewedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [ipAddress] NVARCHAR(100) NULL,

    CONSTRAINT [FK_MOVIE_VIEW_LOG_MOVIE] FOREIGN KEY ([movieId]) REFERENCES [MOVIE]([movieId]),
    CONSTRAINT [FK_MOVIE_VIEW_LOG_USER] FOREIGN KEY ([userId]) REFERENCES [USER]([userId])
);
GO

CREATE TABLE [MOVIE_DAILY_VIEW] (
    [movieId] NVARCHAR(50) NOT NULL,
    [viewDate] DATE NOT NULL,
    [viewCount] INT NOT NULL DEFAULT 0,

    CONSTRAINT [PK_MOVIE_DAILY_VIEW] PRIMARY KEY ([movieId], [viewDate]),
    CONSTRAINT [FK_MOVIE_DAILY_VIEW_MOVIE] FOREIGN KEY ([movieId]) REFERENCES [MOVIE]([movieId])
);
GO


CREATE TABLE [EMAIL_OUTBOX] (
    [emailOutboxId] NVARCHAR(50) PRIMARY KEY,
    [messageType] NVARCHAR(100) NOT NULL,
    [recipientEmail] NVARCHAR(255) NOT NULL,
    [relatedEntityId] NVARCHAR(50) NULL,
    [payloadEncrypted] VARBINARY(MAX) NOT NULL,
    [outboxStatus] NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    [attemptCount] INT NOT NULL DEFAULT 0,
    [nextAttemptAt] DATETIME2 NULL,
    [lastError] NVARCHAR(1000) NULL,
    [createdAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [sentAt] DATETIME2 NULL,

    CONSTRAINT [CK_EMAIL_OUTBOX_STATUS] CHECK ([outboxStatus] IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED')),
    CONSTRAINT [CK_EMAIL_OUTBOX_ATTEMPT_COUNT] CHECK ([attemptCount] >= 0)
);
GO

-- =========================
-- 10. FILTERED UNIQUE INDEXES
-- =========================

CREATE UNIQUE INDEX [UX_PAYMENT_ONE_SUCCESS_PER_BOOKING]
ON [PAYMENT]([bookingId]) WHERE [paymentStatus] = 'SUCCESS';
GO

CREATE UNIQUE INDEX [UX_PAYMENT_TRANSACTION_CODE]
ON [PAYMENT]([transactionCode]) WHERE [transactionCode] IS NOT NULL;
GO

CREATE UNIQUE INDEX [UX_PAYMENT_PROVIDER_TRANSACTION_CODE]
ON [PAYMENT]([providerTransactionCode]) WHERE [providerTransactionCode] IS NOT NULL;
GO

CREATE UNIQUE INDEX [UX_REFUND_PROVIDER_REFUND_CODE]
ON [REFUND]([providerRefundCode]) WHERE [providerRefundCode] IS NOT NULL;
GO

CREATE UNIQUE INDEX [UX_REVIEW_BOOKING]
ON [REVIEW]([bookingId]) WHERE [bookingId] IS NOT NULL;
GO

-- =========================
-- 11. COMMON PERFORMANCE INDEXES
-- =========================

CREATE INDEX [IX_USER_ROLE_ID] ON [USER]([roleId]);
CREATE UNIQUE INDEX [UX_CUSTOMER_PROFILE_IDENTITY_CARD] ON [CUSTOMER_PROFILE]([identityCard]) WHERE [identityCard] IS NOT NULL;
CREATE UNIQUE INDEX [UX_STAFF_PROFILE_IDENTITY_CARD] ON [STAFF_PROFILE]([identityCard]) WHERE [identityCard] IS NOT NULL;
CREATE INDEX [IX_STAFF_PROFILE_CINEMA_ID] ON [STAFF_PROFILE]([cinemaId]);
CREATE INDEX [IX_ROOM_CINEMA_ID] ON [ROOM]([cinemaId]);
CREATE INDEX [IX_SEAT_ROOM_ID] ON [SEAT]([roomId]);
CREATE INDEX [IX_SHOWTIME_MOVIE_ID] ON [SHOWTIME]([movieId]);
CREATE INDEX [IX_SHOWTIME_ROOM_TIME] ON [SHOWTIME]([roomId], [startTime], [endTime]);
CREATE UNIQUE INDEX [UQ_SHOWTIME_ROOM_STARTTIME] ON [SHOWTIME]([roomId], [startTime]);
CREATE INDEX [IX_SHOWTIME_SEAT_SHOWTIME_ID] ON [SHOWTIME_SEAT]([showtimeId]);
CREATE INDEX [IX_SHOWTIME_SEAT_STATUS] ON [SHOWTIME_SEAT]([showtimeId], [seatStatus]);
CREATE INDEX [IX_BOOKING_CUSTOMER_PROFILE_ID] ON [BOOKING]([customerProfileId]);
CREATE INDEX [IX_BOOKING_CREATED_BY_STAFF_PROFILE_ID] ON [BOOKING]([createdByStaffProfileId]);
CREATE INDEX [IX_BOOKING_CHANNEL] ON [BOOKING]([bookingChannel]);
CREATE INDEX [IX_BOOKING_SHOWTIME_ID] ON [BOOKING]([showtimeId]);
CREATE INDEX [IX_BOOKING_STATUS] ON [BOOKING]([bookingStatus]);
CREATE INDEX [IX_BOOKING_FB_FULFILLMENT_STATUS] ON [BOOKING]([fbFulfillmentStatus]);
CREATE INDEX [IX_PAYMENT_BOOKING_ID] ON [PAYMENT]([bookingId]);
CREATE INDEX [IX_REFUND_BOOKING_ID] ON [REFUND]([bookingId]);
CREATE INDEX [IX_REFUND_PAYOUT_ATTEMPT_REFUND_STATUS] ON [REFUND_PAYOUT_ATTEMPT]([refundId], [attemptStatus], [requestedAt]);
CREATE INDEX [IX_EMAIL_OUTBOX_STATUS_NEXT_ATTEMPT] ON [EMAIL_OUTBOX]([outboxStatus], [nextAttemptAt], [createdAt]);
CREATE INDEX [IX_CHECKIN_LOG_TICKET_ID] ON [CHECKIN_LOG]([ticketId]);
CREATE INDEX [IX_CHECKIN_LOG_RAW_QR_CODE] ON [CHECKIN_LOG]([rawQrCode]) WHERE [rawQrCode] IS NOT NULL;
CREATE INDEX [IX_CHECKIN_LOG_SCANNED_BY_USER_TIME] ON [CHECKIN_LOG]([scannedByUserId], [scanTime]);
CREATE INDEX [IX_NOTIFICATION_USER_READ] ON [NOTIFICATION]([userId], [isRead]);
CREATE INDEX [IX_AUDIT_LOG_USER_CREATED_AT] ON [AUDIT_LOG]([userId], [createdAt]);
CREATE INDEX [IX_REVIEW_EDIT_HISTORY_REVIEW_ID] ON [REVIEW_EDIT_HISTORY]([reviewId]);
CREATE INDEX [IX_REVIEW_MODERATION_HISTORY_REVIEW_ID] ON [REVIEW_MODERATION_HISTORY]([reviewId]);
CREATE INDEX [IX_MOVIE_DAILY_VIEW_DATE] ON [MOVIE_DAILY_VIEW]([viewDate]);
CREATE INDEX [IX_MOVIE_HIGHLIGHT_VIEWS] ON [MOVIE]([highlight], [totalViews] DESC);
GO

