/*
Seed data for a local test customer.

The password hash is a placeholder. Replace it with a hash generated by the
backend password hasher when login testing is required.
*/

USE [CinemaBookingDB];
GO

DECLARE @CustomerRoleId NVARCHAR(50);

SELECT @CustomerRoleId = [roleId]
FROM dbo.[ROLE]
WHERE [roleName] = 'CUSTOMER';

IF @CustomerRoleId IS NULL
BEGIN
    SET @CustomerRoleId = 'R01';

    INSERT INTO dbo.[ROLE] ([roleId], [roleName], [description])
    VALUES (@CustomerRoleId, 'CUSTOMER', N'Khach hang mua ve online');
END;

IF NOT EXISTS (
    SELECT 1 FROM dbo.[USER] WHERE [email] = 'customer@gmail.com'
)
BEGIN
    INSERT INTO dbo.[USER]
        ([userId], [roleId], [email], [passwordHash], [fullName],
         [phoneNumber], [status], [emailVerified])
    VALUES
        ('U_CUST_01', @CustomerRoleId, 'customer@gmail.com',
         'AQAAAAEAACcQAAAAE...', N'Nguyen Tan Dung',
         '0901234567', 'ACTIVE', 1);
END;

IF NOT EXISTS (
    SELECT 1 FROM dbo.[CUSTOMER_PROFILE] WHERE [userId] = 'U_CUST_01'
)
BEGIN
    INSERT INTO dbo.[CUSTOMER_PROFILE]
        ([customerProfileId], [userId], [memberLevel], [rewardPoints], [dateOfBirth])
    VALUES
        ('CP01', 'U_CUST_01', 'GOLD', 500, '2005-12-09');
END;
GO
